from flask import Flask, render_template, request, jsonify
import random

app = Flask(__name__)

responses = {
    "default": ["Opción no válida, ingrese el número de la opción que desea.", "intente nuevamente o ingrese 'opciones' para ver el menú de opciones"],
    "opciones": ["Tecnicatura Superior = TS<br>1 - TS en Internet de las Cosas y Sistemas Embebidos<br>2 - TS en Ciencia de Datos e Inteligencia Artificial<br>3 - TS en Análisis de Sistemas<br>4 - TS en Desarrollo de Software<br>5 - TS en Administración Contable<br>6 - TS en Administración Financiera<br>7 - TS en Higiene y Seguridad en el Trabajo<br>8 - TS en Ceremonial y Protocolo<br>9 - TS en Salud y Seguridad Ocupacional en el Trabajo en los Establecimientos de Salud<br>0 - Preguntas Frecuentes"],
    "1": ["Tecnicatura Superior en Internet de las Cosas y Sistemas Embebidos:<br>11 - Perfil Profesional<br>12 - Área Ocupacional<br>13 - Materias<br>14 - Más Info"],
    "11": ["La/el Técnica/o Superior en Internet de las Cosas y Sistemas Embebidos está capacitado para comprender los fundamentos y tecnologías de la disciplinas electrónicas e informáticas, sus aplicaciones actuales y poder seguir el desarrollo y evolución futura, de manera que podrá planear, diseñar, fabricar, evaluar y mantener sistemas y equipos en el ámbito de la Internet de las Cosas y los sistemas embebidos."],
    "12": ["La/el Técnica/o Superior en Internet de las Cosas y Sistemas Embebidos puede ejercer sus funciones profesionales desempeñándose por cuenta propia como responsable de la prestación de servicios profesionales relacionados a equipos e instalaciones de soluciones de Internet de las Cosas y Sistemas Embebidos y También puede desempeñarse en relación de dependencia, en industrias, comercios o empresas del ámbito privado o público que requieran de estos servicios profesionales."],
    "13": ["PRIMER AÑO:<br>Lógica computacional<br>Administración y Gestión de Bases de Datos<br>Elementos de Análisis Matemático<br>Estadística y Probabilidades para Gestión de Datos<br>Inglés I<br>Inglés II<br>Técnicas de Programación<br>PP1: aproximación al campo laboral<br>Comunicación<br><br>SEGUNDO AÑO:<br>Desarrollo de Sistemas de Inteligencia Artificial<br>Ciencia de datos<br>Seguridad para IOT<br>Procesamiento de Aprendizaje Automático<br>PP2: Programación para IOT<br>Arquitectura del nodo IoT<br>Redes, Protocolos e interfaces I<br>Redes, protocolos e interfaces II<br><br>TERCER AÑO:<br>Trabajo, Tecnología y Sociedad<br>Modelizado de minería de datos<br>Inteligencia artificial aplicada a Internet de las Cosas<br>Diseño de infraestructura inteligente para el Internet de las Cosas <br>PP3: Análisis y exploración de datos<br>PP4: Implementación de sistemas inteligentes sobre Internet de las Cosas"],
    "14": ["Para más informacion sobre la carrera puede clickear el siguiente enlace: <a href=http://www.i12.com.ar/i12/wp-content/uploads/2023/03/Anexo-I_Internet-de-las-cosas_IF-2022-42723468-GDEBA-SSEDGCYE-1.pdf>Resolución 3780/22</a>"],
    "2": ["Tecnicatura Superior en Ciencia de Datos e Inteligencia Artificial:<br>21 - Perfil Profesional<br>22 - Área Ocupacional<br>23 - Materias<br>24 - Más Info"],
    "21": ["La/El Técnica/o Superior en Ciencia de Datos e Inteligencia Artificial estará capacitada/o para realizar proyectos de innovación que involucren actividades tanto del campo de la Ciencia de Datos como de la IA. Estará calificada/o para pensar con criterio estadístico situaciones de trabajo que involucren una amplia cantidad de datos, comprendiendo el ciclo de trabajo de la Ciencia de Datos dentro de una organización o para un/a cliente/a particular."],
    "22": ["Este nuevo campo profesional abarca a todas las herramientas, tecnologías, métodos y sistemas requeridos para manejar grandes conjuntos de datos distribuidos, heterogéneos, diversos, tan grandes y complejos que no se pueden analizar con las herramientas y métodos tradicionales de procesamiento y administración de bases de datos. Estas incluyen nuevos algoritmos estadísticos y matemáticos, técnicas de predicción y métodos de modelado, métodos de encriptación, así como enfoques multidisciplinarios y nuevas tecnologías para la recopilación, almacenamiento, análisis e intercambio de datos e información."],
    "23": ["PRIMER AÑO:<br>Lógica computacional<br>Administración y Gestión de Bases de Datos<br>Elementos de Análisis Matemático<br>Estadística y Probabilidades para Gestión de Datos<br>Inglés para Ciencia de Datos e IA 1<br>Inglés para Ciencia de Datos e IA 2<br>Técnicas de Programación<br>PP: Aproximación al campo Laboral<br><br>SEGUNDO AÑO:<br>Desarrollo de Sistemas de Inteligencia Artificial<br>Modelizado de Minería de datos<br>Técnicas de Procesamiento del Habla<br>Procesamiento de Aprendizaje Automático<br>Ciencia de Datos<br>PP: Análisis y Exploraciónde Datos<br><br>TERCER AÑO:<br>Gestión de Proyectos<br>Taller de Comunicación<br>Seminario de Actualización<br>Técnicas de Procesamiento Digital de Imágenes<br>PP: Modelizado de Sistemas de IA<br>PP: Proyecto Integrador<br>Tecnología y ambiente<br>Trabajo, Tecnología y Sociedad"],
    "24": ["Para más informacion sobre la carrera puede clickear el siguiente enlace: <a href=http://www.i12.com.ar/i12/wp-content/uploads/2023/03/Anexo-I-Res-2730-22-Cs-deDatos-e-Inteligencia-Artificial.pdf>Resolución 2730/22</a>"],
    "3": ["Tecnicatura Superior en Análisis de Sistemas:<br>31 - Perfil Profesional<br>32 - Área Ocupacional<br>33 - Materias<br>34 - Más Info"],
    "31": ["El Analista de Sistemas estará capacitado para planificar y gestionar un proyecto de desarrollo, así como también para diagnosticar problemas y diseñar soluciones informáticas de las organizaciones que así lo requieran."],
    "32": ["El Analista de Sistemas podrá desempeñarse en todo tipo de organizaciones que requieran una persona o grupo de personas que dirijan el análisis, diseño e implementación de sistemas de información. Asimismo, podrá trabajar de forma independiente, actuando como consultor para la realización de proyectos relacionados con el análisis, diseño, implementación y/ o seguimiento de sistemas de información. También podrá actuar como auditor de sistemas de información, administrador de bases de datos, miembro de un equipo de aseguramiento de calidad, líder de equipo de pruebas de sistemas y/o conducir grupos de trabajos en estas áreas. "],
    "33": ["PRIMER AÑO:<br>Ingles I<br>Ciencia<br>Tecnología y Sociedad<br>Análisis Matemático I<br>Algebra<br>Algoritmos y estructuras de datos I<br>Sistemas y Organizaciones<br>Arquitectura de Computadores<br>Prácticas Profesionalizantes I<br><br>SEGUNDO AÑO:<br>Inglés II<br>Análisis Matemático II<br>Estadística<br>Ingeniería de Software I<br>Algoritmos y estructuras de datos II<br>Sistemas Operativos<br>Base de Datos<br>Prácticas Profesionalizantes II<br><br>TERCER AÑO:<br>Inglés III<br>Aspectos legales de la Profesión<br>Seminario de actualización<br>Redes y Comunicaciones<br>Ingeniería de Software II<br>Algoritmos y estructuras de datos III<br>Prácticas Profesionalizantes III"],
    "34": ["Para más informacion sobre la carrera puede clickear el siguiente enlace: <a href=http://www.i12.com.ar/i12/wp-content/uploads/2019/12/sistemas679019.pdf>Resolución 6790/19</a>"],
    "4": ["Tecnicatura Superior en Desarrollo de Software:<br>41 - Perfil Profesional<br>42 - Área Ocupacional<br>43 - Materias<br>44 - Más Info"],
    "41": ["El Técnico Superior en Desarrollo de Software estará capacitado para producir artefactos de software, lo que comprende su diseño detallado, construcción -reutilizando elementos existentes o programándolos enteramente- y verificación unitaria, así como su depuración, optimización y mantenimiento. El proceso de desarrollo de software es una tarea grupal, o también individual y muchas veces multidisciplinaria que se organiza por proyectos. Cada proyecto es negociado y acordado con el cliente o usuario y llevado a cabo por un equipo de trabajo constituido “ad-hoc”, conducido y administrado por un líder que mantiene la relación diaria con el cliente o usuario y asume la responsabilidad operativa del proyecto."],
    "42": ["Este técnico se ocupa en organizaciones de diversos tipos. Empresas que realizan desarrollo de software por encargo de organizaciones locales o extranjeras, que proveen software junto con otros servicios de asesoramiento y consultoría, y, en menor número, que desarrollan sus propios productos de software para vender en el país o en el exterior. También en organizaciones dedicadas a otras actividades, pero que producen el software que necesitan para desarrollar sus propias actividades o que integran en productos que venden"],
    "43": ["PRIMER AÑO:<br>Análisis Matemático<br>Administración y gestión de base de datos<br>Introducción a la programación<br>Introducción a las redes de datos<br>Sistemas Digitales<br>Sistemas operativos<br>Laboratorio de Hardware<br>Prácticas Profesionalizantes I<br><br>SEGUNDO AÑO:<br>Inglés I<br>Desarrollo de aplicativos móviles<br>Algebra y lógica<br>Programación<br>Diseño Web<br>Estadística y Probabilidades<br>Desarrollo de sistemas Orientado a Objetos<br>Prácticas Profesionalizantes II<br><br>TERCER AÑO:<br>Inglés II<br>Gestión de Proyectos<br>Desarrollo de sistemas Web<br>Ingeniería de software<br>Metodología de pruebas de sistemas<br>Prácticas Profesionalizantes III"],
    "44": ["Para más informacion sobre la carrera puede clickear el siguiente enlace: <a href=http://www.i12.com.ar/i12/wp-content/uploads/2019/11/DesarrolloSoftware-5847-19.pdf>Resolución 5847/19</a>"],
    "5": ["Tecnicatura Superior en Administración Contable:<br>51 - Perfil Profesional<br>52 - Área Ocupacional<br>53 - Materias<br>54 - Más Info"],
    "51": ["El Técnico Superior en Administración es un profesional que estará capacitado para desarrollar las competencias para: organizar, programar, ejecutar y controlar las operaciones comerciales, financieras y administrativas de la organización; elaborar, controlar y registrar el flujo de información; organizar y planificar los recursos referidos para desarrollar sus actividades interactuando con el entorno y participando en la toma de decisiones relacionadas con sus actividades. Coordinando equipos de trabajo relacionado con su especialidad. Estas competencias serán desarrolladas según las incumbencias y las normas técnicas y legales que rigen su campo profesional. "],
    "52": ["El Técnico Superior en Administración podrá desarrollar sus actividades en grandes empresas, pequeñas y medianas empresas y micro emprendimientos como también en el sector terciario. Los roles del Técnico Superior podrán ser, desde fuertemente específicos, hasta marcadamente globales y de gestión; variando con el tamaño, contenido tecnológico y tipo de tamaño y gestión de la empresa en la que se desempeñe. "],
    "53": ["PRIMER AÑO:<br>Matemática I<br>Computación I<br>Derecho<br>Economía<br>Contabilidad<br>Sociología de la Organización<br>Principios de Administración<br>Metodología de la Investigación<br>Gestión Administrativo Contable<br>Práctica Instrumental y Experiencia Laboral<br>Formación Ética y Mundo Contemporáneo<br><br>SEGUNDO AÑO:<br>Matemática II<br>Estadística<br>Inglés I<br>Computación II<br>Contabilidad II<br>Matemática Financiera<br>Derecho Laboral<br>Práctica Profesional I<br>Derecho Comercial<br>Práctica Instrumental y Experiencia Laboral<br>Formación Ética y Mundo Contemporáneo<br><br>TERCER AÑO:<br>Inglés II<br>Técnica Impositiva y Laboral<br>Régimen Tributario<br>Contabilidad III<br>Costos y Presupuestos<br>Administración Financiera<br>Administración Estratégica<br>Práctica Profesional II<br>Práctica Instrumental y Experiencia Laboral<br>Formación Ética y Mundo Contemporáneo<br>"],
    "54": ["Para más informacion sobre la carrera puede clickear el siguiente enlace: <a href=http://www.i12.com.ar/i12/wp-content/uploads/2019/11/AdmContable_res273_03.pdf>Resolución 273/03</a>"],
    "6": ["Tecnicatura Superior en Administración Financiera:<br>61 - Perfil Profesional<br>62 - Área Ocupacional<br>63 - Materias<br>64 - Más Info"],
    "61": ["El Técnico Superior en Administración es un profesional que estará capacitado para desarrollar las competencias para: organizar, programar, ejecutar y controlar las operaciones comerciales, financieras y administrativas de la organización; elaborar, controlar y registrar el flujo de información; organizar y planificar los recursos referidos para desarrollar sus actividades interactuando con el entorno y participando en la toma de decisiones relacionadas con sus actividades. Coordinando equipos de trabajo relacionado con su especialidad. Estas competencias serán desarrolladas según las incumbencias y las normas técnicas y legales que rigen su campo profesional. "],
    "62": ["El Técnico Superior en Administración podrá desarrollar sus actividades en grandes empresas, pequeñas y medianas empresas y micro emprendimientos como también en el sector terciario. Los roles del Técnico Superior podrán ser, desde fuertemente específicos, hasta marcadamente globales y de gestión; variando con el tamaño, contenido tecnológico y tipo de tamaño y gestión de la empresa en la que se desempeñe."],
    "63": ["PRIMER AÑO:<br>Matemática I<br>Computación I<br>Derecho<br>Economía<br>Contabilidad<br>Sociología de la Organización<br>Principios de Administración<br>Metodología de la Investigación<br>Teoría y Técnica del Seguro<br>Práctica Instrumental y Experiencia Laboral<br>Formación Ética y Mundo Contemporáneo<br><br>SEGUNDO AÑO:<br>Matemática II<br>Estadística<br>Inglés I<br>Computación II<br>Contabilidad II<br>Matemática Financiera<br>Administración Financiera<br>Comercio Internacional<br>Derecho Comercial<br>Práctica Profesional I<br>Práctica Instrumental y Experiencia Laboral<br>Formación Ética y Mundo Contemporáneo<br><br>TERCER AÑO:<br>Inglés II<br>Análisis de Estados Contables<br>Análisis de Proyectos de Inversión<br>Elementos del Mercado Financiero<br>Costos y Presupuestos<br>Técnica y Contabilidad Bancaria<br>Práctica Profesional II<br>"],
    "64": ["Para más informacion sobre la carrera puede clickear el siguiente enlace: <a href=http://www.i12.com.ar/i12/wp-content/uploads/2022/12/tecsupenadminfinancierar277-03.pdf>Resolución 277-03</a>"],
    "7": ["Tecnicatura Superior en Higiene y Seguridad en el Trabajo:<br>71 - Perfil Profesional<br>72 - Área Ocupacional<br>73 - Materias<br>74 - Más Info"],
    "71": ["El Técnico Superior en Seguridad e Higiene en el Trabajo es un profesional competente para la organización, la planificación y organización de actividades, el diseño, la gestión de los recursos de los servicios, la evaluación y control y la capacitación en aspectos inherentes a la higiene y seguridad en el trabajo."],
    "72": ["El Técnico Superior en Seguridad e Higiene en el Trabajo puede desempeñarse en los servicios de Seguridad e Higiene de las más diversas organizaciones, tales como empresas industriales, comerciales, de servicios, de la construcción y actividades laborales en general. Asimismo, es capaz de actuar como asesor externo de dichas organizaciones, brindado el asesoramiento según la normativa y legislación vigente, interviniendo preventivamente para evitar accidentes y enfermedades profesionales."],
    "73": ["PRIMER AÑO:<br>administración de las organizaciones<br>psicología laboral<br>física 1<br>química 1<br>medios de representación<br>medicina del trabajo 1<br>seguridad 1<br>derecho del trabajo<br>práctica profesionalizante 1<br><br>SEGUNDO AÑO:<br>estadística<br>física 2<br>química 2<br>inglés técnico<br>ergonomía<br>seguridad 2<br>higiene laboral y medio ambiente 1<br>medicina del trabajo 2<br>práctica profesionalizante 2<br><br>TERCER AÑO:<br>comunicación y administración de medios<br>capacitación de personal<br>seguridad 3<br>higiene laboral y medio ambiente 2<br>control de la contaminación<br>práctica profesionalizante 3<br>"],
    "74": ["Para más informacion sobre la carrera puede clickear el siguiente enlace: <a href=http://www.i12.com.ar/i12/wp-content/uploads/2019/11/Hig-y-Seg-Tbjo_320-13.pdf>Resolución 320/13</a>"],
    "8": ["Tecnicatura Superior en Ceremonial y Protocolo:<br>81 - Perfil Profesional<br>82 - Área Ocupacional<br>83 - Materias<br>84 - Más Info"],
    "81": ["El Técnico Superior en Ceremonial y Protocolo es un profesional que estará capacitado para desarrollar las siguientes competencias: organizar, coordinar, planificar y supervisar actos, recepciones y ceremonias. Elaborar ordenamientos y precedencias. Asesorar al personas para el desarrollo de encuentros sociales. Asesorar, asistir y acompañar a los titulares de las instituciones. Realizar las comunicaciones correspondientes y desarrollar sus actividades interactuando con el entorno y participando en la toma de decisiones, coordinando equipos de trabajo."],
    "82": ["El Técnico Superior en Ceremonial y Protocolo podrá desarrollar sus actividades en instituciones públicas o privadas (empresas, sindicatos, sociedades comerciales, etc.) Los roles del Técnico Superior podrán ser desde fuertemente específicos, hasta marcadamente globales, variando con el tipo, tamaño, contenido tecnológico y gestional de la organización en la que se desempeñe."],
    "83": ["PRIMER AÑO:<br>inglés i<br>informática<br>historia de las instituciones argentinas i<br>antropología cultural<br>psicología de grupos e institución<br>portugués i<br>ceremonial y protocolo i<br>redacción formal<br>comportamiento social<br>práctica profesional i<br><br>SEGUNDO AÑO:<br>inglés ii<br>historia de la cultura universal<br>historia de las instituciones argentinas ii<br>informática aplicada<br>portugués ii<br>ceremonial y protocolo ii<br>medios de comunicación y protocolo<br>derecho diplomático y consular<br>práctica profesional ii<br><br>TERCER AÑO:<br>inglés iii<br>portugués iii<br>ceremonial y protocolo iii<br>oratoria y locución<br>relaciones públicas<br>práctica profesional iii<br>"],
    "84": ["Para más informacion sobre la carrera puede clickear el siguiente enlace: <a href=http://www.i12.com.ar/i12/wp-content/uploads/2022/09/Resolucion-1623-04.pdf>Resolución 1623-04</a>"],
    "9": ["Tecnicatura Superior en Salud y Seguridad Ocupacional en el Trabajo en los Establecimientos de Salud:<br>91 - Perfil Profesional<br>92 - Materias<br>93 - Más Info"],
    "91": ["En este curso, los profesionales contextualizarán las competencias desarrolladas en el nivel superior, en carreras a fines a la higiene y seguridad en el trabajo"],
    "92": ["MÓDULOS:<br>Salud pública y ocupacional<br>El establecimiento de salid<br>Prevención de riesgos ergonómicos<br>Prevención de riesgos del ambiente de trabajo<br>Prevención de riesgos psicosociales<br>Gestión en salud y seguridad ocupacional<br>Prácticas profesionalizantes"],
    "93": ["Para más informacion sobre la carrera puede clickear el siguiente enlace: <a href=http://www.i12.com.ar/i12/wp-content/uploads/2019/11/CertificacionensaludRes-302-10.pdf>Resolución N° 302/10</a>"],
    "0": ["Dirección:<br>Avda. 7 Nro. 2149 esq. 76<br><br>REQUISITOS DE INGRESO:<br>Haber completado los estudios de Nivel Medio/Secundario o tener certificado de título en trámite, no se acepta el de alumno regular.<br><br>SITIO WEB: <a href=http://www.i12.com.ar/i12/>instituto i12</a>"],
}

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/get_response", methods=["POST"])
def get_response():
    user_input = request.form["user_input"].lower()
    response = responses.get(user_input, random.choice(responses["default"]))
    return jsonify({"response": response})

if __name__ == "__main__":
    app.run(debug=True)
